let currentView="dashboard";
const viewMeta={dashboard:["Overview","Dashboard"],salary:["Income engine","Salary"],calendar:["Work & pay","Calendar"],expenses:["Outgoings","Expenses"],savings:["Build your reserve","Savings"],loans:["Borrowed & lent","Loans"],budget:["Plan ahead","Budget"],goals:["Long-term plans","Goals"],transactions:["Master ledger","Transactions"],reports:["Insights","Reports"],contacts:["People","Contacts"],settings:["Control center","Settings"]};
function applyTheme(){document.documentElement.dataset.theme=state.settings.theme==="dark"?"dark":"";$("#themeBtn").textContent=state.settings.theme==="dark"?"☀":"☾"}
function renderCurrentView(){const [e,t]=viewMeta[currentView]||viewMeta.dashboard;$("#viewEyebrow").textContent=e;$("#viewTitle").textContent=t;$("#app").innerHTML=({dashboard:dashboardView,salary:salaryView,calendar:calendarView,expenses:expensesView,savings:savingsView,loans:loansView,goals:goalsView,transactions:transactionsView,reports:reportsView,settings:settingsView,contacts:contactsView,budget:budgetView}[currentView]||dashboardView)();bindViewEvents();}
function navigate(v){currentView=v;$$("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));renderCurrentView();window.scrollTo({top:0,behavior:"smooth"})}
function bindViewEvents(){
 $$("[data-view]").forEach(b=>b.onclick=()=>navigate(b.dataset.view));
 $$("[data-action]").forEach(b=>b.onclick=()=>actions[b.dataset.action]?.());
 $$("[data-delete-expense]").forEach(b=>b.onclick=()=>{state.expenses=state.expenses.filter(x=>x.id!==b.dataset.deleteExpense);state.transactions=state.transactions.filter(x=>!(x.type==="expense"&&x.id===b.dataset.deleteExpense));saveState();renderCurrentView();AppUI.toast("Expense deleted")});
 $$("[data-delete-goal]").forEach(b=>b.onclick=()=>{state.goals=state.goals.filter(x=>x.id!==b.dataset.deleteGoal);saveState();renderCurrentView()});
 $$("[data-pay]").forEach(b=>b.onclick=()=>markLoan(b.dataset.pay,false));
 $$("[data-receive]").forEach(b=>b.onclick=()=>markLoan(b.dataset.receive,true));
 $$("[data-day]").forEach(b=>b.onclick=()=>calendarStatus(b.dataset.day));
 $$("[data-cal-prev]").forEach(b=>b.onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCurrentView()});
 $$("[data-cal-next]").forEach(b=>b.onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCurrentView()});
 const ts=$("#txSearch"),tt=$("#txType"); if(ts&&tt){const filter=()=>{const q=ts.value.toLowerCase(),type=tt.value;const items=state.transactions.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!type||x.type===type));$("#txTable").innerHTML=txTable(items)};ts.oninput=filter;tt.onchange=filter}
 const tg=$("#themeToggle");if(tg)tg.onchange=()=>{state.settings.theme=tg.checked?"dark":"light";saveState();applyTheme()}
}
function markLoan(id,isLent){const arr=isLent?state.lent:state.loans,x=arr.find(v=>v.id===id);if(!x)return;x.status=isLent?"Received":"Paid";x.paymentDate=today();state.transactions.push({id:uid(),date:today(),type:isLent?"money received":"loan repaid",amount:x.amount,description:`${isLent?"Received from":"Repaid to"} ${x.person}`});saveState();renderCurrentView();AppUI.toast("Status updated")}
const actions={
 "add-expense":addExpenseModal,"salary-settings":salarySettingsModal,"add-loan":()=>loanModal(false),"add-lent":()=>loanModal(true),"edit-savings":savingsModal,"add-goal":goalModal,"add-income":incomeModal,
 "backup":backup,"restore":restore,"export-csv":exportCSV,"print":()=>window.print(),"reset":()=>{if(confirm("Reset all Finance Manager data?")){resetState();applyTheme();renderCurrentView();AppUI.toast("App reset")}},
 "search":()=>{const q=prompt("Search Finance Manager");if(!q)return;navigate("transactions");setTimeout(()=>{const s=$("#txSearch");if(s){s.value=q;s.dispatchEvent(new Event("input"))}},0)}
};
function budgetView(){const m=monthKey(today()),bs=state.budgets.filter(x=>x.month===m);return `<div class="dashboard-head"><div><span class="eyebrow">Plan ahead</span><h2>Budget Planner</h2><p class="subtext">Set monthly spending limits.</p></div><button class="btn primary" data-action="add-budget">＋ Add budget</button></div><div class="grid grid-3 section-gap">${bs.length?bs.map(b=>{const spent=sum(state.expenses.filter(e=>monthKey(e.date)===m&&e.category===b.category),"amount");return `<div class="card"><div class="card-header"><h3>${esc(b.category)}</h3><span class="pill">${Math.round(pct(spent,b.amount))}%</span></div><div class="metric-value">${money(spent)}</div><p class="row-meta">of ${money(b.amount)}</p><div class="progress" style="margin-top:12px"><i style="width:${pct(spent,b.amount)}%"></i></div><p class="row-meta">${money(Math.max(0,b.amount-spent))} remaining</p></div>`}).join(""):`<div class="card"><div class="empty">No budgets for this month.</div></div>`}</div>`}
function budgetModal(){AppUI.formModal("Add monthly budget",`<form><div class="form-grid"><div class="field"><label>Category</label><select name="category">${expenseCategories.map(c=>`<option>${c}</option>`).join("")}</select></div><div class="field"><label>Budget amount</label><input name="amount" type="number" required></div></div><div class="form-actions"><button class="btn primary">Save budget</button></div></form>`,f=>{state.budgets.push({id:uid(),month:monthKey(today()),category:f.get("category"),amount:+f.get("amount")});saveState();AppUI.closeModal();renderCurrentView();AppUI.toast("Budget added")})}
actions["add-budget"]=budgetModal;
function contactsView(){return `<div class="dashboard-head"><div><span class="eyebrow">People</span><h2>Contacts</h2><p class="subtext">Save people you borrow from or lend to.</p></div><button class="btn primary" data-action="add-contact">＋ Add contact</button></div><div class="card section-gap"><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Phone</th><th>Notes</th><th></th></tr></thead><tbody>${state.contacts.length?state.contacts.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.phone||"—")}</td><td>${esc(c.note||"—")}</td><td><button class="btn small danger" data-delete-contact="${c.id}">Delete</button></td></tr>`).join(""):`<tr><td colspan="4"><div class="empty">No contacts yet.</div></td></tr>`}</tbody></table></div></div>`}
function contactModal(){AppUI.formModal("Add contact",`<form><div class="form-grid"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Phone</label><input name="phone"></div><div class="field full"><label>Notes</label><textarea name="note"></textarea></div></div><div class="form-actions"><button class="btn primary">Save contact</button></div></form>`,f=>{state.contacts.push({id:uid(),name:f.get("name"),phone:f.get("phone"),note:f.get("note")});saveState();AppUI.closeModal();renderCurrentView();AppUI.toast("Contact saved")})}
actions["add-contact"]=contactModal;
document.addEventListener("click",e=>{const d=e.target.closest("[data-delete-contact]");if(d){state.contacts=state.contacts.filter(x=>x.id!==d.dataset.deleteContact);saveState();renderCurrentView()}});
$("#menuBtn").onclick=()=>document.body.classList.toggle("menu-open");
$("#themeBtn").onclick=()=>{state.settings.theme=state.settings.theme==="dark"?"light":"dark";saveState();applyTheme();renderCurrentView()};
$("#searchBtn").onclick=actions.search;$("#settingsQuick").onclick=()=>navigate("settings");
applyTheme();renderCurrentView();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}));