function shiftPay(date,settings=state.settings){
 const day=new Date(date+"T12:00:00").getDay(); const names=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; const name=names[day];
 if(!state.salary.schedule[name])return 0;
 const s=state.salary.schedule[name]; let start=Number(s.start.slice(0,2))+Number(s.start.slice(3))/60, end=Number(s.end.slice(0,2))+Number(s.end.slice(3))/60; if(end<=start)end+=24;
 const paid=Math.max(0,end-start-(settings.breakMinutes/60)+(settings.overtimeMinutes/60));
 const night=Math.max(0,Math.min(end,29)-Math.max(start,22)); const morning=Math.max(0,end-Math.max(start,29));
 return night*settings.nightWage+morning*settings.morningWage;
}
function salaryForMonth(m){let d=new Date(m+"-01T12:00:00"), total=0;while(d.getMonth()+1===Number(m.slice(5,7))){const k=d.toISOString().slice(0,10);if(state.salary.workDays[k]==="worked")total+=shiftPay(k);d.setDate(d.getDate()+1)}return total}
function salaryView(){const m=monthKey(today()), worked=Object.entries(state.salary.workDays).filter(([d,v])=>monthKey(d)===m&&v==="worked"), pay=worked.reduce((t,[d])=>t+shiftPay(d),0);return `<div class="dashboard-head"><div><span class="eyebrow">Income engine</span><h2>Salary</h2><p class="subtext">Automatic wage calculation from your work schedule.</p></div><button class="btn primary" data-action="salary-settings">⚙ Wage settings</button></div><div class="grid grid-4">${metric("This month",money(pay),"¥","positive",`${worked.length} worked shifts`)}${metric("Night wage",money(state.settings.nightWage), "22","info","22:00 → 05:00")}${metric("Morning wage",money(state.settings.morningWage),"05","info","05:00 → 06:00")}${metric("Shift break",`${state.settings.breakMinutes}m`,"◷","warning","per shift")}</div><div class="card section-gap"><div class="card-header"><h3>Work schedule</h3><span class="pill">Overtime +${state.settings.overtimeMinutes}m</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Day</th><th>Shift</th><th>Status</th><th>Estimated pay</th></tr></thead><tbody>${["Mon","Tue","Thu","Sun"].map(day=>`<tr><td><b>${day}</b></td><td>${state.salary.schedule[day].start} – ${state.salary.schedule[day].end}</td><td><span class="status success">Scheduled</span></td><td>${money(shiftPay(nextDateForDay(day)))}</td></tr>`).join("")}</tbody></table></div></div>`}
function nextDateForDay(day){const names=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],d=new Date();for(let i=0;i<7;i++){const x=new Date(d);x.setDate(d.getDate()+i);if(names[x.getDay()]===day)return x.toISOString().slice(0,10)}}
function salarySettingsModal(){AppUI.formModal("Wage settings",`<form><div class="form-grid"><div class="field"><label>Night wage / hour</label><input name="night" type="number" value="${state.settings.nightWage}"></div><div class="field"><label>Morning wage / hour</label><input name="morning" type="number" value="${state.settings.morningWage}"></div><div class="field"><label>Break minutes</label><input name="break" type="number" value="${state.settings.breakMinutes}"></div><div class="field"><label>Overtime paid minutes</label><input name="ot" type="number" value="${state.settings.overtimeMinutes}"></div></div><div class="form-actions"><button type="submit" class="btn primary">Save settings</button></div></form>`,f=>{state.settings.nightWage=+f.get("night");state.settings.morningWage=+f.get("morning");state.settings.breakMinutes=+f.get("break");state.settings.overtimeMinutes=+f.get("ot");saveState();AppUI.closeModal();renderCurrentView();AppUI.toast("Salary settings saved")})}